import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import { Action } from 'App/Models'

export default class CreateActionSeeder extends BaseSeeder {
  public async run() {
    await Action.createMany([
      {
        'key': 'F1',
        'name': 'Fire I',
        'level': '2',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 2,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 180,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F2',
        'name': 'Fire II',
        'level': '18',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 4,
        'cast': 3,
        'recast': 2.5,
        'potency': 100,
        'mpCost': 1500,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F3',
        'name': 'Fire III',
        'level': '35',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 4,
        'cast': 3.5,
        'recast': 2.5,
        'potency': 240,
        'mpCost': 2000,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F4',
        'name': 'Fire IV',
        'level': '60',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.8,
        'recast': 2.5,
        'potency': 300,
        'mpCost': 800,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B1',
        'name': 'Blizzard I',
        'level': '1',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 5,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 180,
        'mpCost': 400,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B2',
        'name': 'Blizzard II',
        'level': '12',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 7,
        'cast': 3,
        'recast': 2.5,
        'potency': 100,
        'mpCost': 800,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B3',
        'name': 'Blizzard III',
        'level': '35',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 7,
        'cast': 3.5,
        'recast': 2.5,
        'potency': 240,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B4',
        'name': 'Blizzard IV',
        'level': '58',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 300,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'T1',
        'name': 'Thunder I',
        'level': '6',
        'typeId': 2,
        'elementId': 3,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 30,
        'mpCost': 200,
        'aoe': false,
        'aoeScale': 0,
        'dot': true,
        'dotPotency': 35,
        'dotDuration': 21,
        'cooldown': 0
      },
      {
        'key': 'T2',
        'name': 'Thunder II',
        'level': '26',
        'typeId': 2,
        'elementId': 3,
        'targetId': 2,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 50,
        'mpCost': 400,
        'aoe': true,
        'aoeScale': 0,
        'dot': true,
        'dotPotency': 15,
        'dotDuration': 18,
        'cooldown': 0
      },
      {
        'key': 'T3',
        'name': 'Thunder III',
        'level': '45',
        'typeId': 2,
        'elementId': 3,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 50,
        'mpCost': 400,
        'aoe': false,
        'aoeScale': 0,
        'dot': true,
        'dotPotency': 35,
        'dotDuration': 30,
        'cooldown': 0
      },
      {
        'key': 'T4',
        'name': 'Thunder IV',
        'level': '64',
        'typeId': 2,
        'elementId': 3,
        'targetId': 2,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 50,
        'mpCost': 400,
        'aoe': true,
        'aoeScale': 0,
        'dot': true,
        'dotPotency': 20,
        'dotDuration': 18,
        'cooldown': 0
      },
      {
        'key': 'Scathe',
        'name': 'Scathe',
        'level': '15',
        'typeId': 2,
        'elementId': 4,
        'targetId': 1,
        'aspectId': 1,
        'cast': 0,
        'recast': 2.5,
        'potency': 100,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Freeze',
        'name': 'Freeze',
        'level': '40',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 1,
        'cast': 2.8,
        'recast': 2.5,
        'potency': 120,
        'mpCost': 1000,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Flare',
        'name': 'Flare',
        'level': '50',
        'typeId': 2,
        'elementId': 2,
        'targetId': 2,
        'aspectId': 4,
        'cast': 4,
        'recast': 2.5,
        'potency': 220,
        'mpCost': 10000,
        'aoe': true,
        'aoeScale': 0.6,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Foul',
        'name': 'Foul',
        'level': '70',
        'typeId': 2,
        'elementId': 4,
        'targetId': 2,
        'aspectId': 1,
        'cast': 0,
        'recast': 2.5,
        'potency': 560,
        'mpCost': 0,
        'aoe': true,
        'aoeScale': 0.4,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Despair',
        'name': 'Despair',
        'level': '72',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 4,
        'cast': 3,
        'recast': 2.5,
        'potency': 340,
        'mpCost': 10000,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'US',
        'name': 'Umbral Soul',
        'level': '76',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 5,
        'cast': 0,
        'recast': 2.5,
        'potency': 0,
        'mpCost': 0,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Xeno',
        'name': 'Xenoglossy',
        'level': '80',
        'typeId': 2,
        'elementId': 4,
        'targetId': 1,
        'aspectId': 1,
        'cast': 0,
        'recast': 2.5,
        'potency': 660,
        'mpCost': 0,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'HF',
        'name': 'High Fire',
        'level': '82',
        'typeId': 2,
        'elementId': 2,
        'targetId': 2,
        'aspectId': 4,
        'cast': 3,
        'recast': 2.5,
        'potency': 140,
        'mpCost': 1500,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'HB',
        'name': 'High Blizzard',
        'level': '82',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 7,
        'cast': 3,
        'recast': 2.5,
        'potency': 120,
        'mpCost': 800,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'Para',
        'name': 'Paradox',
        'level': '90',
        'typeId': 2,
        'elementId': 4,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 500,
        'mpCost': 1600,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
    ])
  }
}