import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import { Action } from 'App/Models'

export default class CreateActionSeeder extends BaseSeeder {
  public async run() {
    await Action.createMany([
      {
        'key': 'F1',
        'name': 'Fire I',
        'level': '2',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 180,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F2',
        'name': 'Fire II',
        'level': '18',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 3,
        'cast': 3,
        'recast': 2.5,
        'potency': 100,
        'mpCost': 1500,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F3',
        'name': 'Fire III',
        'level': '35',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 3,
        'cast': 3.5,
        'recast': 2.5,
        'potency': 240,
        'mpCost': 2000,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'F4',
        'name': 'Fire IV',
        'level': '60',
        'typeId': 2,
        'elementId': 2,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.8,
        'recast': 2.5,
        'potency': 300,
        'mpCost': 800,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B1',
        'name': 'Blizzard I',
        'level': '1',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 4,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 180,
        'mpCost': 400,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B2',
        'name': 'Blizzard II',
        'level': '12',
        'typeId': 2,
        'elementId': 1,
        'targetId': 2,
        'aspectId': 6,
        'cast': 3,
        'recast': 2.5,
        'potency': 100,
        'mpCost': 800,
        'aoe': true,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B3',
        'name': 'Blizzard III',
        'level': '35',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 6,
        'cast': 3.5,
        'recast': 2.5,
        'potency': 240,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
      {
        'key': 'B4',
        'name': 'Blizzard IV',
        'level': '58',
        'typeId': 2,
        'elementId': 1,
        'targetId': 1,
        'aspectId': 1,
        'cast': 2.5,
        'recast': 2.5,
        'potency': 300,
        'mpCost': 800,
        'aoe': false,
        'aoeScale': 0,
        'dot': false,
        'dotPotency': 0,
        'dotDuration': 0,
        'cooldown': 0
      },
    ])
  }
}